npmPublishAccess: public

packageExtensions:
  debug@*:
    peerDependenciesMeta:
      supports-color:
        optional: true
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: "*"
  instantiation-di-prototype@*:
    dependencies:
      di: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferInteractive: true

yarnPath: .yarn/releases/yarn-2.3.1.cjs
